In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.linear_model import Ridge

from sklearn.impute import SimpleImputer
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

import sys
sys.path.append('../../modules')
from helper_functions import feature_reduction_x, rating_feature_conversion


C:\Users\Aidan\AppData\Local\Temp\ipykernel_10096\141842256.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/jbyrneirl/BER-Rating-AI-Model/main/data/training/BERRatingData_aa.csv', sep=';', on_bad_lines="skip", low_memory=False)

np.random.seed(0)

#X = df.drop("BerRating", axis='columns')
#X = pd.get_dummies(X)
X = feature_reduction_x(df)
#print(len(list(X.columns)))

imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(X)
X = imp.transform(X)
y = df.BerRating


X_train, X_test, y_train, y_test = train_test_split( X, y, random_state=2)

c:\Users\Aidan\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Users\Aidan\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


In [3]:
model = Ridge()


model.fit(X_train , y_train)
score = model.score(X_test , y_test)

y_hat = model.predict(X_test)

y_con = rating_feature_conversion(y_test.to_numpy())

In [4]:
print("Score: ", score, "\n")

y_hat_con = rating_feature_conversion(y_hat)
cm = confusion_matrix(y_con, y_hat_con)

print("CM")
print(cm)

print(accuracy_score(y_con, y_hat_con))

Score:  0.8659384990658598 

CM
[[  1   6   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 41 157  62   5   4   0   0   0   0   0   0   0   0   0   0]
 [ 23 112 160  74  18   3   0   0   0   0   0   0   0   0   0]
 [  2   9  10  27  16   6   1   0   0   0   0   0   0   0   0]
 [  1   3   6  26  44  25   9   8   2   1   0   0   1   0   0]
 [  1   2   1   3  40  99  47  18   6   2   0   0   0   0   0]
 [  1   1   0   3  12  62 130  82  22   7   2   0   0   0   0]
 [  0   0   0   0   0   9  51  90  57  27   3   2   1   0   0]
 [  0   0   0   0   0   0  10  52  62  43  24   4   3   0   0]
 [  0   0   0   0   0   0   2   4  42  66  41  14   2   3   0]
 [  0   0   0   0   0   0   0   2   6  53  48  31  13   7   0]
 [  0   0   0   0   0   0   0   0   2   5  17  20  18  17   3]
 [  0   0   0   0   0   0   0   0   0   2   3  15  16  27  11]
 [  0   0   0   0   0   0   0   0   0   0   2  11   9  25  18]
 [  0   0   0   0   0   0   0   0   0   0   0   4   3  18  78]]
0.4092
