In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.linear_model import Ridge

from sklearn.impute import SimpleImputer
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

import sys
sys.path.append('../../modules')
from helper_functions import feature_reduction_x, feature_reduction_x2, rating_feature_conversion


C:\Users\Aidan\AppData\Local\Temp\ipykernel_2964\1709899470.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/jbyrneirl/BER-Rating-AI-Model/main/data/training/BERRatingData_aa.csv', sep=';', on_bad_lines="skip", low_memory=False)

np.random.seed(0)

#X = df.drop("BerRating", axis='columns')
#X = pd.get_dummies(X)
#X = feature_reduction_x(df)
X = feature_reduction_x2(df)
#print(len(list(X.columns)))

#imp = SimpleImputer(missing_values=np.nan, strategy='mean')
#imp.fit(X)
#X = imp.transform(X)
y = df.BerRating


X_train, X_test, y_train, y_test = train_test_split( X, y, random_state=2)

c:\Users\Aidan\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['SecondEnerConsumedComment' 'ThirdEnerConsumedComment']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
c:\Users\Aidan\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:112: UserWarning: Features [ 54  65 115 118 119 120 128 129 130] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
c:\Users\Aidan\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:113: RuntimeWarning: invalid value encountered in divide
  f = msb / msw


In [3]:
model = Ridge()


model.fit(X_train , y_train)
score = model.score(X_test , y_test)

y_hat = model.predict(X_test)

y_con = rating_feature_conversion(y_test.to_numpy())

In [4]:
print("Score: ", score, "\n")

y_hat_con = rating_feature_conversion(y_hat)
cm = confusion_matrix(y_con, y_hat_con)

print("CM")
print(cm)

print(accuracy_score(y_con, y_hat_con))

Score:  0.8726097020992669 

CM
[[  0   7   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 63 139  59   5   3   0   0   0   0   0   0   0   0   0   0]
 [ 27  92 181  67  20   3   0   0   0   0   0   0   0   0   0]
 [  3   7  15  19  18   7   1   1   0   0   0   0   0   0   0]
 [  3   1   7  28  39  30   6  10   1   1   0   0   0   0   0]
 [  1   2   1   3  50  95  47  13   4   2   0   1   0   0   0]
 [  2   0   0   4  12  62 141  70  22   6   3   0   0   0   0]
 [  0   0   0   0   0   4  52 101  42  32   8   0   1   0   0]
 [  0   0   0   0   0   0   7  41  75  44  23   6   2   0   0]
 [  0   0   0   0   0   0   2   4  35  74  44  11   1   3   0]
 [  0   0   0   0   0   0   0   1   6  43  62  31  11   6   0]
 [  0   0   0   0   0   0   0   0   0   4  16  23  20  17   2]
 [  0   0   0   0   0   0   0   0   0   1   3  16  20  24  10]
 [  0   0   0   0   0   0   0   0   0   0   2   9  11  25  18]
 [  0   0   0   0   0   0   0   0   0   0   1   3   2  16  81]]
0.43
